### ISSUE TITLE
obtain shell within script

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/virtual-env#2]
The user must type `echo $0` when invoking the Unix script, so that the script knows which shell is running in the terminal. It would be more user-friendly for this to be unnecessary. To implement this:

- [ ] remove the first line of the script, so that it runs under the terminal's shell, not necessarily bash
- [ ] replace the code that checks `$1` with code that determines the current shell and stores it in the `shell` variable
- [ ] remove `` `echo $0` `` from the usage message and from README.md
- [ ] after creating the environment, use `activate`, `activate.csh` or `activate.fish` according to the value of `shell`
- [ ] replace `$2` with `$1` and `$3` with `$2` throughout, as there's one argument less

**Comment by densnow** [comment]
Was having a quick look at this one, it seems its not as straight forward as I might have first thought (I was just thinking environment variables). Done a little bit of reading on this: how robust do you think something like this would be
```bash
current_process=$(ps -hp $$)

if [[ $current_process == *bash* ]]
then
    shell=bash
elif [[ $current_process == *zsh* ]]
then
    shell=zsh
elif [[ $current_process == *tcsh* ]]
then
    shell=tcsh
elif [[ $current_process == *csh* ]]
then
    shell=csh
elif [[ $current_process == *fish* ]]
then
    shell=fish
else
    echo "Unknown shell: $shell"
    exit
fi 
```
It seems to work ok on my machine with bash, but I am not sure how reliable this would be on other platforms/shells. I would need to set something better up for further testing.

**Comment by mwermelinger** [comment]
My shell knowledge isn't enough to know whether this is a robust way. Normally, Linux/macOS comes with various shells, so you can test by typing `zsh` or `tcsh` to start a new shell and then running the script.

**Comment by densnow** [comment]
It turns out not to be very robust, at least when launching a different shell (e.g. `zsh` or `fish` etc) from the current shell then running the script. It shows the executable of the shell to be `/bin/sh` like is mentioned in [this](https://stackoverflow.com/questions/3327013/how-to-determine-the-current-interactive-shell-that-im-in-command-line) SO question. 

The last part of the most popular answer in that question mentions some environment variables that could be uniquely set in certain shells, for example `$shell` will be set to the name of the shell in `tcsh` and `csh`, `$ZSH_NAME` will be set in `zsh` and `$BASH` will be set in `bash` there are others for the other shells too. I will do some testing with this approach when I get bit of time.

**Comment by densnow** [comment]
After a bit more reading I think I have a better understanding of what is going on and what is required. I will just write this out for my own understanding: I believe the script will always be interpreted with `bash` or `/bin/sh` (which is often just a symlink to `bash` on Linux based systems). It is of course written as a bash script so might not be interpreted by different shells without syntax errors anyway. 

What we want, is the executable associated with the process that forked the current process (i.e. the shell that invoked the script), this is obtained from the parent process. The information can be accessed inside the script with a combination of  the `$PPID` (parent process ID) environment variable and the [ps](https://man7.org/linux/man-pages/man1/ps.1.html) command, for example:
```bash
parent_shell=$(ps -o cmd= -q $PPID)
```
I have tested the script out with all of the changes (including changing the variables)  with `bash`, `zsh`, `fish` `tcsh` and `csh`. It seems to work on all but `csh` and I believe this is because on my machine `csh` seems to be an alias for `tcsh` either that or it uses the config from `tcsh`.

I am still fairly new to Github and all of that; if I am about 90% sure this is a robust enough solution is it common practice to just submit the pull request anyway and let other people see and discuss the changes?

**Comment by mwermelinger** [comment]
Even if you remove the shebang line it's still executed under bash?

Yes, you can submit the PR and I'll review it, but not this week as I'm away.

**Comment by densnow** [comment]
If the shebang line is removed and script is invoked through different shell from bash  say `fish` `zsh` etc, the script is executed by `/bin/sh` (at least on my Linux based machine). This, I believe, is the default shell (and just points back to `bash` on Linux in most cases anyway). What I have not tested for is if the default shell is something different to `bash`. I think on Mac the default shell is `zsh`?  So if shebang was left out, then it is possible `zsh` would be interpreting the script. 

The thing is, I don't believe that we need to leave out the shebang pointing to `bash`. We can still have the script interpreted by `bash` and also find the "parent shell" that invoked it and add the alias to the appropriate config.
